[project]
authors = ["Sibbe Bakker <s.l.bakker@uu.nl>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "ERCnet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.2.3,<3"
biopython = ">=1.85,<2"
mafft = ">=7.526,<8"
joblib = ">=1.4.2,<2"
scipy = ">=1.13.1,<2"
orthofinder = ">=3.0.1b1,<4"
iqtree = ">=2.4.0,<3"
treerecs = ">=1.2,<2"
r-base = "4.1.2.*"
r-stringr = ">=1.5.0,<2"
r-ape = "5.6.*"
r-phytools = ">=1.2_0,<2"
r-igraph = ">=1.3.5,<2"
julia = ">=1.8.2,<1.9"
pyvolve = ">=0.9.0,<0.10"
